# pandas

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
days = np.array(["mon","tues","web","thr","fri","sat","sun"])
sales_units = np.array([500,600,700,800,900,1000,300])

In [4]:
sales = pd.Series(data=sales_units,
                  index=days)
sales

mon      500
tues     600
web      700
thr      800
fri      900
sat     1000
sun      300
dtype: int32

In [5]:
type(sales)

pandas.core.series.Series

In [6]:
# in numpy arrays, one can"t give custom index. in series custom index can be give if not it defaultly take 0,1,1

In [7]:
sales.max()

1000

In [8]:
sales.idxmax() # to get the index of the value

'sat'

In [9]:
sales.idxmin() # to get the index of the value

'sun'

## indexing

In [10]:
# find the sales of sunday
sales['sun']

300

In [11]:
sales.iloc[6] # index location(only use numbers )

300

In [12]:
sales.loc["sun"] # lable-based indexing location

300

In [13]:
# replace sunday sales units to 500
sales["sun"]= 500

In [14]:
sales

mon      500
tues     600
web      700
thr      800
fri      900
sat     1000
sun      500
dtype: int32

In [15]:
sales_dict ={"ram":800 ,"same":900,"dam":900}
pd.Series(sales_dict)

ram     800
same    900
dam     900
dtype: int64

In [16]:
sales_dict["ram"]=800
sales_dict

{'ram': 800, 'same': 900, 'dam': 900}

# Slicing

In [17]:
# find the to p days on the sales units 
sales.sort_index?

Signature:
sales.sort_index(
    *,
    axis: 'Axis' = 0,
    level: 'IndexLabel | None' = None,
    ascending: 'bool | Sequence[bool]' = True,
    inplace: 'bool' = False,
    kind: 'SortKind' = 'quicksort',
    na_position: 'NaPosition' = 'last',
    sort_remaining: 'bool' = True,
    ignore_index: 'bool' = False,
    key: 'IndexKeyFunc | None' = None,
) -> 'Series | None'
Docstring:
Sort Series by index labels.

Returns a new Series sorted by label if `inplace` argument is
``False``, otherwise updates the original series and returns None.

Parameters
----------
axis : {0 or 'index'}
    Unused. Parameter needed for compatibility with DataFrame.
level : int, optional
    If not None, sort on values in specified index level(s).
ascending : bool or list-like of bools, default True
    Sort ascending vs. descending. When the index is a MultiIndex the
    sort direction can be controlled for each level individually.
inplace : bool, default False
    If True, perform operation in-place.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
    Choice of sorting algorithm. See also :func:`numpy.sort` for more
    information. 'mergesort' and 'stable' are the only stable algorithms. For
    DataFrames, this option is only applied when sorting on a single
    column or label.
na_position : {'first', 'last'}, default 'last'
    If 'first' puts NaNs at the beginning, 'last' puts NaNs at the end.
    Not implemented for MultiIndex.
sort_remaining : bool, default True
    If True and sorting by level and index is multilevel, sort by other
    levels too (in order) after sorting by specified level.
ignore_index : bool, default False
    If True, the resulting axis will be labeled 0, 1, …, n - 1.
key : callable, optional
    If not None, apply the key function to the index values
    before sorting. This is similar to the `key` argument in the
    builtin :meth:`sorted` function, with the notable difference that
    this `key` function should be *vectorized*. It should expect an
    ``Index`` and return an ``Index`` of the same shape.

Returns
-------
Series or None
    The original Series sorted by the labels or None if ``inplace=True``.

See Also
--------
DataFrame.sort_index: Sort DataFrame by the index.
DataFrame.sort_values: Sort DataFrame by the value.
Series.sort_values : Sort Series by the value.

Examples
--------
>>> s = pd.Series(['a', 'b', 'c', 'd'], index=[3, 2, 1, 4])
>>> s.sort_index()
1    c
2    b
3    a
4    d
dtype: object

Sort Descending

>>> s.sort_index(ascending=False)
4    d
3    a
2    b
1    c
dtype: object

By default NaNs are put at the end, but use `na_position` to place
them at the beginning

>>> s = pd.Series(['a', 'b', 'c', 'd'], index=[3, 2, 1, np.nan])
>>> s.sort_index(na_position='first')
NaN     d
 1.0    c
 2.0    b
 3.0    a
dtype: object

Specify index level to sort

>>> arrays = [np.array(['qux', 'qux', 'foo', 'foo',
...                     'baz', 'baz', 'bar', 'bar']),
...           np.array(['two', 'one', 'two', 'one',
...                     'two', 'one', 'two', 'one'])]
>>> s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=arrays)
>>> s.sort_index(level=1)
bar  one    8
baz  one    6
foo  one    4
qux  one    2
bar  two    7
baz  two    5
foo  two    3
qux  two    1
dtype: int64

Does not sort by remaining levels when sorting by levels

>>> s.sort_index(level=1, sort_remaining=False)
qux  one    2
foo  one    4
baz  one    6
bar  one    8
qux  two    1
foo  two    3
baz  two    5
bar  two    7
dtype: int64

Apply a key function before sorting

>>> s = pd.Series([1, 2, 3, 4], index=['A', 'b', 'C', 'd'])
>>> s.sort_index(key=lambda x : x.str.lower())
A    1
b    2
C    3
d    4
dtype: int64
File:      d:\anaconda python\lib\site-packages\pandas\core\series.py
Type:      method

In [18]:
sales.sort_values(ascending=False).head(5)

sat     1000
fri      900
thr      800
web      700
tues     600
dtype: int32

In [19]:
sales_target = 400
# find the days where sales was not met 
sal = sales>sales_target
sal

mon     True
tues    True
web     True
thr     True
fri     True
sat     True
sun     True
dtype: bool

In [20]:
days[sal]

array(['mon', 'tues', 'web', 'thr', 'fri', 'sat', 'sun'], dtype='<U4')

In [21]:
# extract  only weeldays sales units 
weekday_sales = sales[:5]

print(weekday_sales)

mon     500
tues    600
web     700
thr     800
fri     900
dtype: int32

# pandas dataframes 

it is used to store the data in table formate

In [22]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3
File:           d:\anaconda python\lib\site-packages\pandas\core\frame.py
Type:           type
Subclasses:     SubclassedDataFrame

In [23]:
import pandas as pd
employees_dict = {
    "emp_id": ["E001", "E002", "E003", "E004", "E005", "E006"],
    "name": ["Arun", "Priya", "Rahul", "Sneha", "Karthik", "Divya"],
    "age": [25, 30, 28, 35, 27, 32],
    "gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "department": ["IT", "HR", "Finance", "IT", "Marketing", "Finance"],
    "designation": [
        "Data Analyst",
        "HR Executive",
        "Accountant",
        "Software Engineer",
        "Marketing Executive",
        "Financial Analyst"
    ],
    "salary": [45000, 50000, 55000, 70000, 48000, 65000],
    "experience": [2, 5, 4, 8, 3, 6],
    "city": ["Chennai", "Coimbatore", "Bangalore", "Hyderabad", "Chennai", "Pune"],
    "joining_year": [2023, 2020, 2021, 2018, 2022, 2019],
    "performance_rating": [4.2, 4.8, 4.1, 4.9, 3.8, 4.5],
    "bonus": [30000, 50000, 40000, 70000, 25000, 60000]
}

In [24]:
empoyees= pd.DataFrame(data=employees_dict)
empoyees

,emp_id,name,age,gender,department,designation,salary,experience,city,joining_year,performance_rating,bonus
0,E001,Arun,25,Male,IT,Data Analyst,45000,2,Chennai,2023,4.2,30000
1,E002,Priya,30,Female,HR,HR Executive,50000,5,Coimbatore,2020,4.8,50000
2,E003,Rahul,28,Male,Finance,Accountant,55000,4,Bangalore,2021,4.1,40000
3,E004,Sneha,35,Female,IT,Software Engineer,70000,8,Hyderabad,2018,4.9,70000
4,E005,Karthik,27,Male,Marketing,Marketing Executive,48000,3,Chennai,2022,3.8,25000
5,E006,Divya,32,Female,Finance,Financial Analyst,65000,6,Pune,2019,4.5,60000

In [25]:
type(empoyees)

pandas.core.frame.DataFrame

In [26]:
# set employee id as index
employees = empoyees.set_index("emp_id")
employees

,name,age,gender,department,designation,salary,experience,city,joining_year,performance_rating,bonus
emp_id,,,,,,,,,,,
E001,Arun,25,Male,IT,Data Analyst,45000,2,Chennai,2023,4.2,30000
E002,Priya,30,Female,HR,HR Executive,50000,5,Coimbatore,2020,4.8,50000
E003,Rahul,28,Male,Finance,Accountant,55000,4,Bangalore,2021,4.1,40000
E004,Sneha,35,Female,IT,Software Engineer,70000,8,Hyderabad,2018,4.9,70000
E005,Karthik,27,Male,Marketing,Marketing Executive,48000,3,Chennai,2022,3.8,25000
E006,Divya,32,Female,Finance,Financial Analyst,65000,6,Pune,2019,4.5,60000

In [27]:
#extract the employess id  e004 salary
employees.loc["E004", "salary"]

70000

In [28]:
employees.iloc[3,5]

70000

In [29]:
#extract divya's age 

employees.loc["E006","age"]

32

In [30]:
employees[employees["name"] == "Divya"]

,name,age,gender,department,designation,salary,experience,city,joining_year,performance_rating,bonus
emp_id,,,,,,,,,,,
E006,Divya,32,Female,Finance,Financial Analyst,65000,6,Pune,2019,4.5,60000

In [31]:
employees[employees["name"] == "Divya"].index[0]

'E006'

In [32]:
employees[employees["age"] > 28]

,name,age,gender,department,designation,salary,experience,city,joining_year,performance_rating,bonus
emp_id,,,,,,,,,,,
E002,Priya,30,Female,HR,HR Executive,50000,5,Coimbatore,2020,4.8,50000
E004,Sneha,35,Female,IT,Software Engineer,70000,8,Hyderabad,2018,4.9,70000
E006,Divya,32,Female,Finance,Financial Analyst,65000,6,Pune,2019,4.5,60000

In [33]:
empoyees.index

RangeIndex(start=0, stop=6, step=1)

In [34]:
employees.isna()

,name,age,gender,department,designation,salary,experience,city,joining_year,performance_rating,bonus
emp_id,,,,,,,,,,,
E001,False,False,False,False,False,False,False,False,False,False,False
E002,False,False,False,False,False,False,False,False,False,False,False
E003,False,False,False,False,False,False,False,False,False,False,False
E004,False,False,False,False,False,False,False,False,False,False,False
E005,False,False,False,False,False,False,False,False,False,False,False
E006,False,False,False,False,False,False,False,False,False,False,False

In [35]:
employees.isna().any()

name                  False
age                   False
gender                False
department            False
designation           False
salary                False
experience            False
city                  False
joining_year          False
performance_rating    False
bonus                 False
dtype: bool

In [36]:
employees["salary"].idxmax()

'E004'

In [37]:
employees.loc[_, 'name']

'Sneha'

In [38]:
employees["experience"]

emp_id
E001    2
E002    5
E003    4
E004    8
E005    3
E006    6
Name: experience, dtype: int64

# dataframe slicing

In [39]:
#extract emp003 and emp004' details
employees.loc["E003":"E004",:]

,name,age,gender,department,designation,salary,experience,city,joining_year,performance_rating,bonus
emp_id,,,,,,,,,,,
E003,Rahul,28,Male,Finance,Accountant,55000,4,Bangalore,2021,4.1,40000
E004,Sneha,35,Female,IT,Software Engineer,70000,8,Hyderabad,2018,4.9,70000

In [40]:
employees.loc["E003":"E004","name":"age"]

         name  age
emp_id
E003    Rahul   28
E004    Sneha   35

In [41]:
employees.head()

,name,age,gender,department,designation,salary,experience,city,joining_year,performance_rating,bonus
emp_id,,,,,,,,,,,
E001,Arun,25,Male,IT,Data Analyst,45000,2,Chennai,2023,4.2,30000
E002,Priya,30,Female,HR,HR Executive,50000,5,Coimbatore,2020,4.8,50000
E003,Rahul,28,Male,Finance,Accountant,55000,4,Bangalore,2021,4.1,40000
E004,Sneha,35,Female,IT,Software Engineer,70000,8,Hyderabad,2018,4.9,70000
E005,Karthik,27,Male,Marketing,Marketing Executive,48000,3,Chennai,2022,3.8,25000

In [42]:

#loading the excel data as pd dataframe 
sales_data = pd.read_excel("sales.xlsx")
sales_data

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,49,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02
2,50,293,2012-10-01,High,27,244.5700,0.01,NaN,46.7075,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03
3,80,483,2011-07-10,High,30,4965.7595,0.08,NaN,1198.9710,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12
4,85,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,7765,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.1800,150.98,...,Mick Brown,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09
8395,7766,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.2500,17.07,...,Mick Brown,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11
8396,7906,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.0500,22.23,...,Frank Hawley,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10
8397,7907,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.2360,65.99,...,Frank Hawley,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09
8398,7914,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.4300,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11

In [43]:
sales_data.head() # this will display all the first 5 rowas and it can be also changed.

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,49,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02
2,50,293,2012-10-01,High,27,244.5700,0.01,NaN,46.7075,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03
3,80,483,2011-07-10,High,30,4965.7595,0.08,NaN,1198.9710,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12
4,85,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30

In [44]:
sales_data.head(10)

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,49,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02
2,50,293,2012-10-01,High,27,244.5700,0.01,NaN,46.7075,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03
3,80,483,2011-07-10,High,30,4965.7595,0.08,NaN,1198.9710,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12
4,85,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30
5,86,515,2010-08-28,Not Specified,21,146.6900,0.05,Regular Air,4.4300,6.64,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Furniture,Office Furnishings,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,Small Pack,0.37,2010-08-30
6,97,613,2011-06-17,High,12,93.5400,0.03,Regular Air,-54.0385,7.30,...,Carl Jackson,Nunavut,Nunavut,Corporate,Office Supplies,Binders and Binder Accessories,"Angle-D Binders with Locking Rings, Label Holders",Small Box,0.38,2011-06-17
7,98,613,2011-06-17,High,22,905.0800,0.09,Regular Air,127.7000,42.76,...,Carl Jackson,Nunavut,Nunavut,Corporate,Office Supplies,Storage & Organization,"SAFCO Mobile Desk Side File, Wire Frame",Small Box,NaN,2011-06-18
8,103,643,2011-03-24,High,21,2781.8200,0.07,Express Air,-695.2600,138.14,...,Monica Federle,Nunavut,Nunavut,Corporate,Office Supplies,Storage & Organization,"SAFCO Commercial Wire Shelving, Black",Large Box,NaN,2011-03-25
9,107,678,2010-02-26,Low,44,228.4100,0.07,Regular Air,-226.3600,4.98,...,Dorothy Badders,Nunavut,Nunavut,Home Office,Office Supplies,Paper,Xerox 198,Small Box,0.38,2010-02-26

In [45]:
sales_data.tail()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
8394,7765,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.180,150.98,...,Mick Brown,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09
8395,7766,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.250,17.07,...,Mick Brown,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11
8396,7906,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.050,22.23,...,Frank Hawley,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10
8397,7907,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.236,65.99,...,Frank Hawley,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09
8398,7914,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.430,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11

In [46]:
sales_data.duplicated().sum()

0

In [47]:
sales_data.iloc[-1]

Row ID                                                               7914
Order ID                                                            56581
Order Date                                            2009-02-08 00:00:00
Order Priority                                                       High
Order Quantity                                                         20
Sales                                                             2026.01
Discount                                                              0.1
Ship Mode                                                     Express Air
Profit                                                             580.43
Unit Price                                                         105.98
Shipping Cost                                                       13.99
Customer Name                                             Grant Donatelli
Province                                                          Alberta
Region                                                               West
Customer Segment                                                 Consumer
Product Category                                                Furniture
Product Sub-Category                                   Office Furnishings
Product Name            Tenex 46" x 60" Computer Anti-Static Chairmat,...
Product Container                                              Medium Box
Product Base Margin                                                  0.65
Ship Date                                             2009-02-11 00:00:00
Name: 8398, dtype: object

In [48]:
sales_data.loc[8399]= sales_data.iloc[-1]

In [49]:
sales_data.duplicated().sum()

1

In [50]:
sales_data.duplicated().any()

True

In [51]:
sales_data.loc[8400]= sales_data.iloc[-1]

In [52]:
sales_data.duplicated().sum()

2

In [53]:
## extracting duplicated records
sales_data[sales_data.duplicated()]

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
8399,7914,56581,2009-02-08,High,20,2026.01,0.1,Express Air,580.43,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11
8400,7914,56581,2009-02-08,High,20,2026.01,0.1,Express Air,580.43,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11

In [54]:
## removing duplicated records 
sales_data = sales_data.drop_duplicates()
sales_data

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,49,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02
2,50,293,2012-10-01,High,27,244.5700,0.01,NaN,46.7075,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03
3,80,483,2011-07-10,High,30,4965.7595,0.08,NaN,1198.9710,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12
4,85,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,7765,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.1800,150.98,...,Mick Brown,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09
8395,7766,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.2500,17.07,...,Mick Brown,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11
8396,7906,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.0500,22.23,...,Frank Hawley,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10
8397,7907,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.2360,65.99,...,Frank Hawley,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09
8398,7914,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.4300,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11

In [55]:
# check for null values
sales_data.isnull()

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8395,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8396,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8397,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8398,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [56]:
sales_data.isnull().sum()

Row ID                   0
Order ID                 0
Order Date               0
Order Priority           0
Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                4
Profit                   0
Unit Price               0
Shipping Cost            3
Customer Name            0
Province                 0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64

## replacing null values

In [57]:
sales_data["Ship Mode"].info()

<class 'pandas.core.series.Series'>
Index: 8399 entries, 0 to 8398
Series name: Ship Mode
Non-Null Count  Dtype
--------------  -----
8395 non-null   object
dtypes: object(1)
memory usage: 131.2+ KB

In [58]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8399 entries, 0 to 8398
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                8399 non-null   int64
 1   Order ID              8399 non-null   int64
 2   Order Date            8399 non-null   datetime64[ns]
 3   Order Priority        8399 non-null   object
 4   Order Quantity        8399 non-null   int64
 5   Sales                 8399 non-null   float64
 6   Discount              8399 non-null   float64
 7   Ship Mode             8395 non-null   object
 8   Profit                8399 non-null   float64
 9   Unit Price            8399 non-null   float64
 10  Shipping Cost         8396 non-null   float64
 11  Customer Name         8399 non-null   object
 12  Province              8399 non-null   object
 13  Region                8399 non-null   object
 14  Customer Segment      8399 non-null   object
 15  Product Category      8399 non-null   object
 16  Product Sub-Category  8399 non-null   object
 17  Product Name          8399 non-null   object
 18  Product Container     8399 non-null   object
 19  Product Base Margin   8336 non-null   float64
 20  Ship Date             8399 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(6), int64(3), object(10)
memory usage: 1.4+ MB

In [59]:
most_common_ship_mode = sales_data["Ship Mode"].mode()[0]
most_common_ship_mode

'Regular Air'

In [60]:
sales_data["Ship Mode"] = sales_data["Ship Mode"].fillna(most_common_ship_mode)

D:\TEMP\ipykernel_13740\2406509015.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_data["Ship Mode"] = sales_data["Ship Mode"].fillna(most_common_ship_mode)

In [61]:
sales_data.isnull().sum()

Row ID                   0
Order ID                 0
Order Date               0
Order Priority           0
Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                0
Profit                   0
Unit Price               0
Shipping Cost            3
Customer Name            0
Province                 0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64

In [62]:
sales_data["Shipping Cost"].info()

<class 'pandas.core.series.Series'>
Index: 8399 entries, 0 to 8398
Series name: Shipping Cost
Non-Null Count  Dtype
--------------  -----
8396 non-null   float64
dtypes: float64(1)
memory usage: 131.2 KB

In [63]:
cost = sales_data["Shipping Cost"].median()
cost

6.07

In [64]:
sales_data["Shipping Cost"] = sales_data["Shipping Cost"].fillna(cost)
sales_data

D:\TEMP\ipykernel_13740\395944029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_data["Shipping Cost"] = sales_data["Shipping Cost"].fillna(cost)

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,49,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02
2,50,293,2012-10-01,High,27,244.5700,0.01,Regular Air,46.7075,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03
3,80,483,2011-07-10,High,30,4965.7595,0.08,Regular Air,1198.9710,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12
4,85,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,7765,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.1800,150.98,...,Mick Brown,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09
8395,7766,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.2500,17.07,...,Mick Brown,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11
8396,7906,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.0500,22.23,...,Frank Hawley,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10
8397,7907,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.2360,65.99,...,Frank Hawley,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09
8398,7914,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.4300,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11

In [65]:
sales_data.isnull().sum()

Row ID                   0
Order ID                 0
Order Date               0
Order Priority           0
Order Quantity           0
Sales                    0
Discount                 0
Ship Mode                0
Profit                   0
Unit Price               0
Shipping Cost            0
Customer Name            0
Province                 0
Region                   0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Name             0
Product Container        0
Product Base Margin     63
Ship Date                0
dtype: int64

In [66]:
sales_data

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,49,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02
2,50,293,2012-10-01,High,27,244.5700,0.01,Regular Air,46.7075,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03
3,80,483,2011-07-10,High,30,4965.7595,0.08,Regular Air,1198.9710,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12
4,85,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,7765,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.1800,150.98,...,Mick Brown,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09
8395,7766,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.2500,17.07,...,Mick Brown,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11
8396,7906,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.0500,22.23,...,Frank Hawley,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10
8397,7907,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.2360,65.99,...,Frank Hawley,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09
8398,7914,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.4300,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11

In [67]:
sales_data.dropna?

Signature:
sales_data.dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False,
) -> 'DataFrame | None'
Docstring:
Remove missing values.

See the :ref:`User Guide <missing_data>` for more on which values are
considered missing, and how to work with missing data.

Parameters
----------
axis : {0 or 'index', 1 or 'columns'}, default 0
    Determine if rows or columns which contain missing values are
    removed.

    * 0, or 'index' : Drop rows which contain missing values.
    * 1, or 'columns' : Drop columns which contain missing value.

    Only a single axis is allowed.

how : {'any', 'all'}, default 'any'
    Determine if row or column is removed from DataFrame, when we have
    at least one NA or all NA.

    * 'any' : If any NA values are present, drop that row or column.
    * 'all' : If all values are NA, drop that row or column.

thresh : int, optional
    Require that many non-NA values. Cannot be combined with how.
subset : column label or sequence of labels, optional
    Labels along other axis to consider, e.g. if you are dropping rows
    these would be a list of columns to include.
inplace : bool, default False
    Whether to modify the DataFrame rather than creating a new one.
ignore_index : bool, default ``False``
    If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

    .. versionadded:: 2.0.0

Returns
-------
DataFrame or None
    DataFrame with NA entries dropped from it or None if ``inplace=True``.

See Also
--------
DataFrame.isna: Indicate missing values.
DataFrame.notna : Indicate existing (non-missing) values.
DataFrame.fillna : Replace missing values.
Series.dropna : Drop missing values.
Index.dropna : Drop missing indices.

Examples
--------
>>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
...                             pd.NaT]})
>>> df
       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Drop the rows where at least one element is missing.

>>> df.dropna()
     name        toy       born
1  Batman  Batmobile 1940-04-25

Drop the columns where at least one element is missing.

>>> df.dropna(axis='columns')
       name
0    Alfred
1    Batman
2  Catwoman

Drop the rows where all elements are missing.

>>> df.dropna(how='all')
       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Keep only the rows with at least 2 non-NA values.

>>> df.dropna(thresh=2)
       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

Define in which columns to look for missing values.

>>> df.dropna(subset=['name', 'toy'])
       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT
File:      d:\anaconda python\lib\site-packages\pandas\core\frame.py
Type:      method

In [68]:
#removing rows where there is no  values  in product margin column

sales_data = sales_data.dropna()

In [69]:
sales_data.isna().sum()

Row ID                  0
Order ID                0
Order Date              0
Order Priority          0
Order Quantity          0
Sales                   0
Discount                0
Ship Mode               0
Profit                  0
Unit Price              0
Shipping Cost           0
Customer Name           0
Province                0
Region                  0
Customer Segment        0
Product Category        0
Product Sub-Category    0
Product Name            0
Product Container       0
Product Base Margin     0
Ship Date               0
dtype: int64

In [70]:
sales_data

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,...,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,49,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02
2,50,293,2012-10-01,High,27,244.5700,0.01,Regular Air,46.7075,8.69,...,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03
3,80,483,2011-07-10,High,30,4965.7595,0.08,Regular Air,1198.9710,195.99,...,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12
4,85,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,...,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,7765,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.1800,150.98,...,Mick Brown,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09
8395,7766,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.2500,17.07,...,Mick Brown,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11
8396,7906,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.0500,22.23,...,Frank Hawley,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10
8397,7907,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.2360,65.99,...,Frank Hawley,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09
8398,7914,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.4300,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11

In [71]:
len(sales_data)

8336

# analytics in pandas

In [72]:
# find the average of profit 
sales_data["Profit"]

0       -213.2500
1        457.8100
2         46.7075
3       1198.9710
4         30.9400
          ...
8394    -323.1800
8395      22.2500
8396     343.0500
8397    -159.2360
8398     580.4300
Name: Profit, Length: 8336, dtype: float64

In [73]:
sales_data["Profit"].mean()

178.41158858337334

In [74]:
import numpy as np
np.round(sales_data["Profit"].mean(),1)

178.4

In [75]:
# find the averaage profit of state
sales_data.groupby("Region")["Profit"].mean()

Region
Atlantic                 216.346863
Northwest Territories    235.270287
Nunavut                   19.821539
Ontario                  194.298707
Prarie                   183.974198
Quebec                   178.914610
West                     144.268068
Yukon                    138.042366
Name: Profit, dtype: float64

In [76]:
# find the averaage profit and sales  of state
sales_data.groupby("Region")[["Profit", "Sales","Discount"]].mean()

                           Profit        Sales  Discount
Region
Atlantic               216.346863  1845.798125  0.050729
Northwest Territories  235.270287  1966.031173  0.050179
Nunavut                 19.821539  1398.597151  0.051974
Ontario                194.298707  1665.275714  0.049151
Prarie                 183.974198  1637.291512  0.049752
Quebec                 178.914610  1918.728619  0.049716
West                   144.268068  1792.803576  0.048782
Yukon                  138.042366  1802.316737  0.050724

In [77]:
#find the average product , total_sales and total orders by region
sales_agg = sales_data.groupby("Region").agg({
    "Profit": "mean",
    "Sales": "sum",
    "Order ID": "count"
})
sales_agg

                           Profit         Sales  Order ID
Region
Atlantic               216.346863  1.975004e+06      1070
Northwest Territories  235.270287  7.667522e+05       390
Nunavut                 19.821539  1.062934e+05        76
Ontario                194.298707  3.019145e+06      1813
Prarie                 183.974198  2.773572e+06      1694
Quebec                 178.914610  1.487015e+06       775
West                   144.268068  3.547958e+06      1979
Yukon                  138.042366  9.714487e+05       539

In [78]:
## rename column to match the values in the dataframe
sales_agg.rename?

Signature:
sales_agg.rename(
    mapper: 'Renamer | None' = None,
    *,
    index: 'Renamer | None' = None,
    columns: 'Renamer | None' = None,
    axis: 'Axis | None' = None,
    copy: 'bool | None' = None,
    inplace: 'bool' = False,
    level: 'Level | None' = None,
    errors: 'IgnoreRaise' = 'ignore',
) -> 'DataFrame | None'
Docstring:
Rename columns or index labels.

Function / dict values must be unique (1-to-1). Labels not contained in
a dict / Series will be left as-is. Extra labels listed don't throw an
error.

See the :ref:`user guide <basics.rename>` for more.

Parameters
----------
mapper : dict-like or function
    Dict-like or function transformations to apply to
    that axis' values. Use either ``mapper`` and ``axis`` to
    specify the axis to target with ``mapper``, or ``index`` and
    ``columns``.
index : dict-like or function
    Alternative to specifying axis (``mapper, axis=0``
    is equivalent to ``index=mapper``).
columns : dict-like or function
    Alternative to specifying axis (``mapper, axis=1``
    is equivalent to ``columns=mapper``).
axis : {0 or 'index', 1 or 'columns'}, default 0
    Axis to target with ``mapper``. Can be either the axis name
    ('index', 'columns') or number (0, 1). The default is 'index'.
copy : bool, default True
    Also copy underlying data.

    .. note::
        The `copy` keyword will change behavior in pandas 3.0.
        `Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        will be enabled by default, which means that all methods with a
        `copy` keyword will use a lazy copy mechanism to defer the copy and
        ignore the `copy` keyword. The `copy` keyword will be removed in a
        future version of pandas.

        You can already get the future behavior and improvements through
        enabling copy on write ``pd.options.mode.copy_on_write = True``
inplace : bool, default False
    Whether to modify the DataFrame rather than creating a new one.
    If True then value of copy is ignored.
level : int or level name, default None
    In case of a MultiIndex, only rename labels in the specified
    level.
errors : {'ignore', 'raise'}, default 'ignore'
    If 'raise', raise a `KeyError` when a dict-like `mapper`, `index`,
    or `columns` contains labels that are not present in the Index
    being transformed.
    If 'ignore', existing keys will be renamed and extra keys will be
    ignored.

Returns
-------
DataFrame or None
    DataFrame with the renamed axis labels or None if ``inplace=True``.

Raises
------
KeyError
    If any of the labels is not found in the selected axis and
    "errors='raise'".

See Also
--------
DataFrame.rename_axis : Set the name of the axis.

Examples
--------
``DataFrame.rename`` supports two calling conventions

* ``(index=index_mapper, columns=columns_mapper, ...)``
* ``(mapper, axis={'index', 'columns'}, ...)``

We *highly* recommend using keyword arguments to clarify your
intent.

Rename columns using a mapping:

>>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> df.rename(columns={"A": "a", "B": "c"})
   a  c
0  1  4
1  2  5
2  3  6

Rename index using a mapping:

>>> df.rename(index={0: "x", 1: "y", 2: "z"})
   A  B
x  1  4
y  2  5
z  3  6

Cast index labels to a different type:

>>> df.index
RangeIndex(start=0, stop=3, step=1)
>>> df.rename(index=str).index
Index(['0', '1', '2'], dtype='object')

>>> df.rename(columns={"A": "a", "B": "b", "C": "c"}, errors="raise")
Traceback (most recent call last):
KeyError: ['C'] not found in axis

Using axis-style parameters:

>>> df.rename(str.lower, axis='columns')
   a  b
0  1  4
1  2  5
2  3  6

>>> df.rename({1: 2, 2: 4}, axis='index')
   A  B
0  1  4
2  2  5
4  3  6
File:      d:\anaconda python\lib\site-packages\pandas\core\frame.py
Type:      method

In [79]:
sales_agg.rename(mapper={"Profit":"avg profit",
                        "Sales":"total_sales",
                        "Order ID":"total_order"})

                           Profit         Sales  Order ID
Region
Atlantic               216.346863  1.975004e+06      1070
Northwest Territories  235.270287  7.667522e+05       390
Nunavut                 19.821539  1.062934e+05        76
Ontario                194.298707  3.019145e+06      1813
Prarie                 183.974198  2.773572e+06      1694
Quebec                 178.914610  1.487015e+06       775
West                   144.268068  3.547958e+06      1979
Yukon                  138.042366  9.714487e+05       539

In [80]:
# find the averafe shipping cost and total order priority
#rename the columns that align with the values in the result
sales_data.groupby(["Region", "Order Priority","Shipping Cost"]).size()

Region    Order Priority  Shipping Cost
Atlantic  Critical        0.49             1
                          0.50             6
                          0.70             9
                          0.93             1
                          0.99             1
                                          ..
Yukon     Not Specified   51.94            1
                          52.20            1
                          54.92            1
                          56.14            2
                          58.20            1
Length: 5132, dtype: int64

In [81]:
sales_data = sales_data.drop(columns=("Row ID"))

In [82]:
sales_data

,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,Shipping Cost,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,35.00,Muhammed MacIntyre,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20
1,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,68.02,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02
2,293,2012-10-01,High,27,244.5700,0.01,Regular Air,46.7075,8.69,2.99,Barry French,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03
3,483,2011-07-10,High,30,4965.7595,0.08,Regular Air,1198.9710,195.99,3.99,Clay Rozendal,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12
4,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,5.94,Carlos Soltero,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.1800,150.98,66.27,Mick Brown,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09
8395,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.2500,17.07,8.13,Mick Brown,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11
8396,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.0500,22.23,5.08,Frank Hawley,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10
8397,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.2360,65.99,8.99,Frank Hawley,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09
8398,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.4300,105.98,13.99,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11

In [83]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8336 entries, 0 to 8398
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order ID              8336 non-null   int64
 1   Order Date            8336 non-null   datetime64[ns]
 2   Order Priority        8336 non-null   object
 3   Order Quantity        8336 non-null   int64
 4   Sales                 8336 non-null   float64
 5   Discount              8336 non-null   float64
 6   Ship Mode             8336 non-null   object
 7   Profit                8336 non-null   float64
 8   Unit Price            8336 non-null   float64
 9   Shipping Cost         8336 non-null   float64
 10  Customer Name         8336 non-null   object
 11  Province              8336 non-null   object
 12  Region                8336 non-null   object
 13  Customer Segment      8336 non-null   object
 14  Product Category      8336 non-null   object
 15  Product Sub-Category  8336 non-null   object
 16  Product Name          8336 non-null   object
 17  Product Container     8336 non-null   object
 18  Product Base Margin   8336 non-null   float64
 19  Ship Date             8336 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(6), int64(2), object(10)
memory usage: 1.3+ MB

In [84]:
sales_data['Ship Date'] - sales_data['Order Date']

0      7 days
1      1 days
2      2 days
3      2 days
4      2 days
        ...
8394   0 days
8395   2 days
8396   2 days
8397   1 days
8398   3 days
Length: 8336, dtype: timedelta64[ns]

In [85]:
sales_data['Ship Time'] = sales_data['Ship Date'] - sales_data['Order Date']

In [86]:
sales_data

,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,Shipping Cost,...,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date,Ship Time
0,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,35.00,...,Nunavut,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20,7 days
1,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,68.02,...,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02,1 days
2,293,2012-10-01,High,27,244.5700,0.01,Regular Air,46.7075,8.69,2.99,...,Nunavut,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03,2 days
3,483,2011-07-10,High,30,4965.7595,0.08,Regular Air,1198.9710,195.99,3.99,...,Nunavut,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12,2 days
4,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,5.94,...,Nunavut,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30,2 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.1800,150.98,66.27,...,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09,0 days
8395,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.2500,17.07,8.13,...,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11,2 days
8396,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.0500,22.23,5.08,...,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10,2 days
8397,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.2360,65.99,8.99,...,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09,1 days
8398,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.4300,105.98,13.99,...,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11,3 days

In [88]:
# create a average ship time by order priroity
average_shiptime = sales_data.groupby("Order Priority").agg({
    "Ship Time": "mean"
})

average_shiptime

                               Ship Time
Order Priority
Critical       1 days 12:22:38.490566037
High           1 days 09:55:41.538461538
Low            4 days 05:56:25.137507314
Medium         1 days 11:17:54.461538461
Not Specified  1 days 11:11:46.095353047

In [89]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8336 entries, 0 to 8398
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order ID              8336 non-null   int64
 1   Order Date            8336 non-null   datetime64[ns]
 2   Order Priority        8336 non-null   object
 3   Order Quantity        8336 non-null   int64
 4   Sales                 8336 non-null   float64
 5   Discount              8336 non-null   float64
 6   Ship Mode             8336 non-null   object
 7   Profit                8336 non-null   float64
 8   Unit Price            8336 non-null   float64
 9   Shipping Cost         8336 non-null   float64
 10  Customer Name         8336 non-null   object
 11  Province              8336 non-null   object
 12  Region                8336 non-null   object
 13  Customer Segment      8336 non-null   object
 14  Product Category      8336 non-null   object
 15  Product Sub-Category  8336 non-null   object
 16  Product Name          8336 non-null   object
 17  Product Container     8336 non-null   object
 18  Product Base Margin   8336 non-null   float64
 19  Ship Date             8336 non-null   datetime64[ns]
 20  Ship Time             8336 non-null   timedelta64[ns]
dtypes: datetime64[ns](2), float64(6), int64(2), object(10), timedelta64[ns](1)
memory usage: 1.4+ MB

In [91]:
sales_data['ship time (days)'] = sales_data['Ship Time'].map(lambda timedelta: timedelta.days)

In [92]:
sales_data.head()

,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,Shipping Cost,...,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date,Ship Time,ship time (days)
0,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,35.00,...,Nunavut,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20,7 days,7
1,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,68.02,...,Nunavut,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02,1 days,1
2,293,2012-10-01,High,27,244.5700,0.01,Regular Air,46.7075,8.69,2.99,...,Nunavut,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03,2 days,2
3,483,2011-07-10,High,30,4965.7595,0.08,Regular Air,1198.9710,195.99,3.99,...,Nunavut,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12,2 days,2
4,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,5.94,...,Nunavut,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30,2 days,2

In [94]:
# create a average ship time by order priroity
average_shiptime = sales_data.groupby("Order Priority").agg({
    "ship time (days)": "mean"
})

average_shiptime

                ship time (days)
Order Priority
Critical                1.515723
High                    1.413675
Low                     4.247513
Medium                  1.470769
Not Specified           1.466506

In [99]:
# the company has a policy that every order that has a ship time of more than 2 days to be 
# tagged as 'delay', 'no delay' otherwise'
# add a new coloumn 'delay status' that should hold aonly two values 'delay'/'no delay'
# based on the ship time (days) column
sales_data['delay status']=sales_data['ship time (days)'].map(lambda timedelta: 'delay' if timedelta > 2 else 'no delay')

In [100]:
sales_data.tail()

,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,Shipping Cost,...,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date,Ship Time,ship time (days),delay status
8394,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.180,150.98,66.27,...,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09,0 days,0,no delay
8395,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.250,17.07,8.13,...,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11,2 days,2,no delay
8396,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.050,22.23,5.08,...,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10,2 days,2,no delay
8397,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.236,65.99,8.99,...,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09,1 days,1,no delay
8398,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.430,105.98,13.99,...,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11,3 days,3,delay

In [101]:
np.where(sales_data['ship time (days)']> 2,"delay", "no delay")

array(['delay', 'no delay', 'no delay', ..., 'no delay', 'no delay',
       'delay'], dtype='<U8')

In [104]:
pd.crosstab(
    sales_data['Ship Mode'],
    sales_data['Order Priority'],
    margins=True,
    margins_name='Total'
)

Order Priority  Critical  High   Low  Medium  Not Specified  Total
Ship Mode
Delivery Truck       222   244   249     205            210   1130
Express Air          197   209   189     201            177    973
Regular Air         1171  1302  1271    1219           1270   6233
Total               1590  1755  1709    1625           1657   8336

In [102]:
pd.crosstab(
    sales_data['Ship Mode'],
    sales_data['delay status'],
    margins=True,
    margins_name='Total',
)

delay status    delay  no delay  Total
Ship Mode
Delivery Truck    219       911   1130
Express Air       168       805    973
Regular Air      1138      5095   6233
Total            1525      6811   8336

In [105]:
pd.crosstab(
    sales_data['Ship Mode'],
    sales_data['Order Priority'],
    normalize='index'
) * 100

Order Priority   Critical       High        Low     Medium  Not Specified
Ship Mode
Delivery Truck  19.646018  21.592920  22.035398  18.141593      18.584071
Express Air     20.246660  21.479959  19.424460  20.657760      18.191161
Regular Air     18.787101  20.888818  20.391465  19.557196      20.375421

In [103]:
pd.crosstab(sales_data['Ship Mode'], sales_data['Order Priority'])

Order Priority  Critical  High   Low  Medium  Not Specified
Ship Mode
Delivery Truck       222   244   249     205            210
Express Air          197   209   189     201            177
Regular Air         1171  1302  1271    1219           1270

In [106]:
sales_data.groupby(['Ship Mode', 'Order Priority'])['Order ID'].count().unstack()

Order Priority  Critical  High   Low  Medium  Not Specified
Ship Mode
Delivery Truck       222   244   249     205            210
Express Air          197   209   189     201            177
Regular Air         1171  1302  1271    1219           1270

In [109]:
#find which ship mode has delay and no delay count by different ship mode
pd.crosstab(sales_data['delay status'], sales_data['Ship Mode'])

Ship Mode     Delivery Truck  Express Air  Regular Air
delay status
delay                    219          168         1138
no delay                 911          805         5095

In [110]:
pd.crosstab?

Signature:
pd.crosstab(
    index,
    columns,
    values=None,
    rownames=None,
    colnames=None,
    aggfunc=None,
    margins: 'bool' = False,
    margins_name: 'Hashable' = 'All',
    dropna: 'bool' = True,
    normalize: "bool | Literal[0, 1, 'all', 'index', 'columns']" = False,
) -> 'DataFrame'
Docstring:
Compute a simple cross tabulation of two (or more) factors.

By default, computes a frequency table of the factors unless an
array of values and an aggregation function are passed.

Parameters
----------
index : array-like, Series, or list of arrays/Series
    Values to group by in the rows.
columns : array-like, Series, or list of arrays/Series
    Values to group by in the columns.
values : array-like, optional
    Array of values to aggregate according to the factors.
    Requires `aggfunc` be specified.
rownames : sequence, default None
    If passed, must match number of row arrays passed.
colnames : sequence, default None
    If passed, must match number of column arrays passed.
aggfunc : function, optional
    If specified, requires `values` be specified as well.
margins : bool, default False
    Add row/column margins (subtotals).
margins_name : str, default 'All'
    Name of the row/column that will contain the totals
    when margins is True.
dropna : bool, default True
    Do not include columns whose entries are all NaN.
normalize : bool, {'all', 'index', 'columns'}, or {0,1}, default False
    Normalize by dividing all values by the sum of values.

    - If passed 'all' or `True`, will normalize over all values.
    - If passed 'index' will normalize over each row.
    - If passed 'columns' will normalize over each column.
    - If margins is `True`, will also normalize margin values.

Returns
-------
DataFrame
    Cross tabulation of the data.

See Also
--------
DataFrame.pivot : Reshape data based on column values.
pivot_table : Create a pivot table as a DataFrame.

Notes
-----
Any Series passed will have their name attributes used unless row or column
names for the cross-tabulation are specified.

Any input passed containing Categorical data will have **all** of its
categories included in the cross-tabulation, even if the actual data does
not contain any instances of a particular category.

In the event that there aren't overlapping indexes an empty DataFrame will
be returned.

Reference :ref:`the user guide <reshaping.crosstabulations>` for more examples.

Examples
--------
>>> a = np.array(["foo", "foo", "foo", "foo", "bar", "bar",
...               "bar", "bar", "foo", "foo", "foo"], dtype=object)
>>> b = np.array(["one", "one", "one", "two", "one", "one",
...               "one", "two", "two", "two", "one"], dtype=object)
>>> c = np.array(["dull", "dull", "shiny", "dull", "dull", "shiny",
...               "shiny", "dull", "shiny", "shiny", "shiny"],
...              dtype=object)
>>> pd.crosstab(a, [b, c], rownames=['a'], colnames=['b', 'c'])
b   one        two
c   dull shiny dull shiny
a
bar    1     2    1     0
foo    2     2    1     2

Here 'c' and 'f' are not represented in the data and will not be
shown in the output because dropna is True by default. Set
dropna=False to preserve categories with no data.

>>> foo = pd.Categorical(['a', 'b'], categories=['a', 'b', 'c'])
>>> bar = pd.Categorical(['d', 'e'], categories=['d', 'e', 'f'])
>>> pd.crosstab(foo, bar)
col_0  d  e
row_0
a      1  0
b      0  1
>>> pd.crosstab(foo, bar, dropna=False)
col_0  d  e  f
row_0
a      1  0  0
b      0  1  0
c      0  0  0
File:      d:\anaconda python\lib\site-packages\pandas\core\reshape\pivot.py
Type:      function

In [111]:
pd.crosstab(sales_data['delay status'], sales_data['Ship Mode'], normalize="index")

Ship Mode     Delivery Truck  Express Air  Regular Air
delay status
delay               0.143607     0.110164     0.746230
no delay            0.133754     0.118191     0.748055

In [112]:
pd.crosstab(sales_data['delay status'], sales_data['Ship Mode'], normalize="columns")

Ship Mode     Delivery Truck  Express Air  Regular Air
delay status
delay               0.193805     0.172662     0.182577
no delay            0.806195     0.827338     0.817423

In [113]:
 #find out if there is anu assiciation between region and delay statis
pd.crosstab(sales_data['Region'],sales_data["delay status"])

delay status           delay  no delay
Region
Atlantic                 210       860
Northwest Territories     57       333
Nunavut                   17        59
Ontario                  352      1461
Prarie                   278      1416
Quebec                   139       636
West                     355      1624
Yukon                    117       422

In [114]:
sales_data

,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,Shipping Cost,...,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date,Ship Time,ship time (days),delay status
0,3,2010-10-13,Low,6,261.5400,0.04,Regular Air,-213.2500,38.94,35.00,...,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,2010-10-20,7 days,7,delay
1,293,2012-10-01,High,49,10123.0200,0.07,Delivery Truck,457.8100,208.16,68.02,...,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2012-10-02,1 days,1,no delay
2,293,2012-10-01,High,27,244.5700,0.01,Regular Air,46.7075,8.69,2.99,...,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,2012-10-03,2 days,2,no delay
3,483,2011-07-10,High,30,4965.7595,0.08,Regular Air,1198.9710,195.99,3.99,...,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,2011-07-12,2 days,2,no delay
4,515,2010-08-28,Not Specified,19,394.2700,0.08,Regular Air,30.9400,21.78,5.94,...,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,2010-08-30,2 days,2,no delay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,55558,2010-08-09,Medium,8,1294.0400,0.05,Delivery Truck,-323.1800,150.98,66.27,...,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,2010-08-09,0 days,0,no delay
8395,55558,2010-08-09,Medium,23,392.5700,0.04,Regular Air,22.2500,17.07,8.13,...,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,2010-08-11,2 days,2,no delay
8396,56550,2011-04-08,Not Specified,37,823.7800,0.03,Express Air,343.0500,22.23,5.08,...,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,2011-04-10,2 days,2,no delay
8397,56550,2011-04-08,Not Specified,8,469.8375,0.00,Regular Air,-159.2360,65.99,8.99,...,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,2011-04-09,1 days,1,no delay
8398,56581,2009-02-08,High,20,2026.0100,0.10,Express Air,580.4300,105.98,13.99,...,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,2009-02-11,3 days,3,delay

In [115]:
# find out if there is any association between container and delay status
# it is probable that large container shipment causes delay in shipping 
pd.crosstab(sales_data['Product Container'],sales_data['delay status'])

delay status       delay  no delay
Product Container
Jumbo Box            103       425
Jumbo Drum           118       494
Large Box             72       308
Medium Box            61       290
Small Box            780      3561
Small Pack           155       801
Wrap Bag             236       932

In [119]:
# Calculate delay percentage per container type and sort from highest to lowest
delay_rates = (
    pd.crosstab(
        sales_data['Product Container'],
        sales_data['delay status'],
        normalize='columns',
    )['delay']
    * 100
)

delay_rates.sort_values(ascending=False)

Product Container
Small Box     51.147541
Wrap Bag      15.475410
Small Pack    10.163934
Jumbo Drum     7.737705
Jumbo Box      6.754098
Large Box      4.721311
Medium Box     4.000000
Name: delay, dtype: float64

In [121]:
sales_data.to_excel("sales_data_processed.xlsx")