## pandas

pandas is a data processing library for working with 2 d data like tables ,etc
pandas is a combination of  "panel"+ "data"

pandas has two core data structures 
* series 
* datafeames

series object is used as a coloumn of a table. dataframe is tge table itself.so in a dataframe, everey coloumn is a series object

### creating a series object

In [3]:
import pandas as pd

In [6]:
pd.series?

Object `pd.series` not found.

In [13]:
import pandas as pd
import numpy as np

amount = np.array([500, 700, 900, 1000, 7000, 5000, 2000])
weekdays = np.array(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'])

sales = pd.Series(
    data=amount,
    index=weekdays,
    name="sales",
    dtype=np.int16
)

print(sales)

monday        500
tuesday       700
wednesday     900
thursday     1000
friday       7000
saturday     5000
sunday       2000
Name: sales, dtype: int16

In [14]:
dir(sales)  # attributes and methods of series object

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'friday',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'monday',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'saturday',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'sunday',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'thursday',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tuesday',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'wednesday',
 'where',
 'xs']

In [15]:
sales.values #as a numpy array

array([ 500,  700,  900, 1000, 7000, 5000, 2000], dtype=int16)

In [16]:
sales.index # extract index of the series objects

Index(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday',
       'sunday'],
      dtype='object')

In [18]:
sales.isna() # to identify null values

monday       False
tuesday      False
wednesday    False
thursday     False
friday       False
saturday     False
sunday       False
Name: sales, dtype: bool

In [20]:
sales.isna().any() # outputs ture if any of the aavlues is true

False

In [21]:
sales.isna().all() # outputs ture if all of the aavlues is true

False

In [22]:
sales.argmin()

0

In [23]:
sales.argmax

<bound method IndexOpsMixin.argmax of monday        500
tuesday       700
wednesday     900
thursday     1000
friday       7000
saturday     5000
sunday       2000
Name: sales, dtype: int16>

In [24]:
sales.idxmin() # index of the minimium value

'monday'

In [25]:
sales.idxmax()   #c index of the maximum value

'friday'

In [26]:
sales.mean()

2442.8571428571427

In [28]:
sales.sort_values()

monday        500
tuesday       700
wednesday     900
thursday     1000
sunday       2000
saturday     5000
friday       7000
Name: sales, dtype: int16

In [31]:
sorted_ values = sales.sort_values(ascending = False)

friday       7000
saturday     5000
sunday       2000
thursday     1000
wednesday     900
tuesday       700
monday        500
Name: sales, dtype: int16

In [36]:
sales + 100 # we ll be able to +,-,*,% like numpy also in series

monday        600
tuesday       800
wednesday    1000
thursday     1100
friday       7100
saturday     5100
sunday       2100
Name: sales, dtype: int16

In [43]:
def discount(sales):
    if sales >= 1000:
        discount_amount = sales * 0.10   # 10% discount
    elif sales >= 500:
        discount_amount = sales * 0.05   # 5% discount
    else:
        discount_amount = 0

    remaining_amount = sales - discount_amount
    return discount_amount, remaining_amount

In [44]:
sales.map(discount)

monday         (25.0, 475.0)
tuesday        (35.0, 665.0)
wednesday      (45.0, 855.0)
thursday       (50.0, 950.0)
friday       (350.0, 6650.0)
saturday     (250.0, 4750.0)
sunday       (100.0, 1900.0)
Name: sales, dtype: object

### indexing in pandas

In [47]:
#sales.loc?

In [48]:
sales.loc["sunday"]

2000

In [52]:
sales.loc["monday" : "wednesday"]

monday       500
tuesday      700
wednesday    900
Name: sales, dtype: int16

In [53]:
amount

array([ 500,  700,  900, 1000, 7000, 5000, 2000])

In [54]:
amount[3:5]

array([1000, 7000])

In [58]:
sales.iloc[4]

7000

In [59]:
sales.iloc[4:6]

friday      7000
saturday    5000
Name: sales, dtype: int16

In [65]:
#sales.where?

In [66]:
sales.where(sales< 1000) # it is like an if statement

monday       500.0
tuesday      700.0
wednesday    900.0
thursday       NaN
friday         NaN
saturday       NaN
sunday         NaN
Name: sales, dtype: float64

In [68]:
(~sales.where(sales < 1000).isna())

monday        True
tuesday       True
wednesday     True
thursday     False
friday       False
saturday     False
sunday       False
Name: sales, dtype: bool

In [70]:
sales.loc[(~sales.where(sales < 1000).isna())]

monday       500
tuesday      700
wednesday    900
Name: sales, dtype: int16

In [73]:
fd = np.linspace(1,4,50)
print(fd)

[1.         1.06122449 1.12244898 1.18367347 1.24489796 1.30612245
 1.36734694 1.42857143 1.48979592 1.55102041 1.6122449  1.67346939
 1.73469388 1.79591837 1.85714286 1.91836735 1.97959184 2.04081633
 2.10204082 2.16326531 2.2244898  2.28571429 2.34693878 2.40816327
 2.46938776 2.53061224 2.59183673 2.65306122 2.71428571 2.7755102
 2.83673469 2.89795918 2.95918367 3.02040816 3.08163265 3.14285714
 3.20408163 3.26530612 3.32653061 3.3877551  3.44897959 3.51020408
 3.57142857 3.63265306 3.69387755 3.75510204 3.81632653 3.87755102
 3.93877551 4.        ]

## dataframe

DataFrame is used to repreesnt 2 darrays in a tabular formate

In [77]:
#pd.DataFrame?

In [80]:
import pandas as pd

data = [
    ["P001", "Laptop", "Electronics", 5, 20, 55000],
    ["P002", "Shirt", "Clothing", 10, 50, 1200],
    ["P003", "Book", "Stationery", 15, 100, 300],
    ["P004", "Mobile", "Electronics", 8, 30, 20000],
    ["P005", "Jeans", "Clothing", 12, 40, 1800],
    ["P006", "Pen", "Stationery", 25, 200, 20],
    ["P007", "Tablet", "Electronics", 6, 25, 15000],
    ["P008", "Jacket", "Clothing", 7, 35, 2500],
    ["P009", "Notebook", "Stationery", 20, 150, 80],
    ["P010", "Headphones", "Electronics", 9, 45, 2000],
    ["P011", "T-shirt", "Clothing", 18, 60, 700],
    ["P012", "Marker", "Stationery", 30, 180, 50],
    ["P013", "Monitor", "Electronics", 4, 15, 12000],
    ["P014", "Sweater", "Clothing", 11, 55, 2200],
    ["P015", "Folder", "Stationery", 22, 140, 60],
    ["P016", "Keyboard", "Electronics", 10, 50, 1500],
    ["P017", "Shorts", "Clothing", 14, 65, 900],
    ["P018", "Eraser", "Stationery", 35, 250, 10],
    ["P019", "Mouse", "Electronics", 13, 70, 800],
    ["P020", "Cap", "Clothing", 16, 80, 400],
    ["P021", "Stapler", "Stationery", 19, 90, 150],
    ["P022", "Printer", "Electronics", 3, 10, 8000],
    ["P023", "Scarf", "Clothing", 9, 45, 600],
    ["P024", "Glue", "Stationery", 28, 160, 40],
    ["P025", "Speaker", "Electronics", 6, 30, 3000]
]

pro = pd.DataFrame(data, columns=[
    "product_code",
    "product_name",
    "category",
    "quantity",
    "available_stock",
    "price"
])

print(pro)

   product_code product_name     category  quantity  available_stock  price
0          P001       Laptop  Electronics         5               20  55000
1          P002        Shirt     Clothing        10               50   1200
2          P003         Book   Stationery        15              100    300
3          P004       Mobile  Electronics         8               30  20000
4          P005        Jeans     Clothing        12               40   1800
5          P006          Pen   Stationery        25              200     20
6          P007       Tablet  Electronics         6               25  15000
7          P008       Jacket     Clothing         7               35   2500
8          P009     Notebook   Stationery        20              150     80
9          P010   Headphones  Electronics         9               45   2000
10         P011      T-shirt     Clothing        18               60    700
11         P012       Marker   Stationery        30              180     50
12         P013      Monitor  Electronics         4               15  12000
13         P014      Sweater     Clothing        11               55   2200
14         P015       Folder   Stationery        22              140     60
15         P016     Keyboard  Electronics        10               50   1500
16         P017       Shorts     Clothing        14               65    900
17         P018       Eraser   Stationery        35              250     10
18         P019        Mouse  Electronics        13               70    800
19         P020          Cap     Clothing        16               80    400
20         P021      Stapler   Stationery        19               90    150
21         P022      Printer  Electronics         3               10   8000
22         P023        Scarf     Clothing         9               45    600
23         P024         Glue   Stationery        28              160     40
24         P025      Speaker  Electronics         6               30   3000

In [81]:
dir(pro)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'available_stock',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'category',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'price',
 'prod',
 'product',
 'product_code',
 'product_name',
 'quantile',
 'quantity',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [82]:
# extractin the category coloumn
pro["category"]

0     Electronics
1        Clothing
2      Stationery
3     Electronics
4        Clothing
5      Stationery
6     Electronics
7        Clothing
8      Stationery
9     Electronics
10       Clothing
11     Stationery
12    Electronics
13       Clothing
14     Stationery
15    Electronics
16       Clothing
17     Stationery
18    Electronics
19       Clothing
20     Stationery
21    Electronics
22       Clothing
23     Stationery
24    Electronics
Name: category, dtype: object

In [83]:
pro["category"].value_counts()

category
Electronics    9
Clothing       8
Stationery     8
Name: count, dtype: int64

In [84]:
pro["category"].value_counts(normalize=True)

category
Electronics    0.36
Clothing       0.32
Stationery     0.32
Name: proportion, dtype: float64

In [85]:
# loc[] 
pro.loc[0]

product_code              P001
product_name            Laptop
category           Electronics
quantity                     5
available_stock             20
price                    55000
Name: 0, dtype: object

In [86]:
print(pro)

   product_code product_name     category  quantity  available_stock  price
0          P001       Laptop  Electronics         5               20  55000
1          P002        Shirt     Clothing        10               50   1200
2          P003         Book   Stationery        15              100    300
3          P004       Mobile  Electronics         8               30  20000
4          P005        Jeans     Clothing        12               40   1800
5          P006          Pen   Stationery        25              200     20
6          P007       Tablet  Electronics         6               25  15000
7          P008       Jacket     Clothing         7               35   2500
8          P009     Notebook   Stationery        20              150     80
9          P010   Headphones  Electronics         9               45   2000
10         P011      T-shirt     Clothing        18               60    700
11         P012       Marker   Stationery        30              180     50
12         P013      Monitor  Electronics         4               15  12000
13         P014      Sweater     Clothing        11               55   2200
14         P015       Folder   Stationery        22              140     60
15         P016     Keyboard  Electronics        10               50   1500
16         P017       Shorts     Clothing        14               65    900
17         P018       Eraser   Stationery        35              250     10
18         P019        Mouse  Electronics        13               70    800
19         P020          Cap     Clothing        16               80    400
20         P021      Stapler   Stationery        19               90    150
21         P022      Printer  Electronics         3               10   8000
22         P023        Scarf     Clothing         9               45    600
23         P024         Glue   Stationery        28              160     40
24         P025      Speaker  Electronics         6               30   3000

In [2]:
pro.set_index("product_code", inplace=True) # this function sets the index and also delets the previous valuse in that place if we use inpace = true

NameError: name 'pro' is not defined

In [107]:
print(pro.head())
print(pro.index)

             product_name     category  quantity  available_stock  price
product_code
P001               Laptop  Electronics         5               20  55000
P002                Shirt     Clothing        10               50   1200
P003                 Book   Stationery        15              100    300
P004               Mobile  Electronics         8               30  20000
P005                Jeans     Clothing        12               40   1800
Index(['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008', 'P009',
       'P010', 'P011', 'P012', 'P013', 'P014', 'P015', 'P016', 'P017', 'P018',
       'P019', 'P020', 'P021', 'P022', 'P023', 'P024', 'P025'],
      dtype='object', name='product_code')

In [108]:
pro.loc["P001"]

product_name            Laptop
category           Electronics
quantity                     5
available_stock             20
price                    55000
Name: P001, dtype: object

In [8]:
import pandas as pd

data = [
    ["P001", "Laptop", "Electronics", 5, 20, 55000],
    ["P002", "Shirt", "Clothing", 10, 50, 1200],
    ["P003", "Book", "Stationery", 15, 100, 300],
    ["P004", "Mobile", "Electronics", 8, 30, 20000],
    ["P005", "Jeans", "Clothing", 12, 40, 1800],
    ["P006", "Pen", "Stationery", 25, 200, 20],
    ["P007", "Tablet", "Electronics", 6, 25, 15000],
    ["P008", "Jacket", "Clothing", 7, 35, 2500],
    ["P009", "Notebook", "Stationery", 20, 150, 80],
    ["P010", "Headphones", "Electronics", 9, 45, 2000],
    ["P011", "T-shirt", "Clothing", 18, 60, 700],
    ["P012", "Marker", "Stationery", 30, 180, 50],
    ["P013", "Monitor", "Electronics", 4, 15, 12000],
    ["P014", "Sweater", "Clothing", 11, 55, 2200],
    ["P015", "Folder", "Stationery", 22, 140, 60],
    ["P016", "Keyboard", "Electronics", 10, 50, 1500],
    ["P017", "Shorts", "Clothing", 14, 65, 900],
    ["P018", "Eraser", "Stationery", 35, 250, 10],
    ["P019", "Mouse", "Electronics", 13, 70, 800],
    ["P020", "Cap", "Clothing", 16, 80, 400],
    ["P021", "Stapler", "Stationery", 19, 90, 150],
    ["P022", "Printer", "Electronics", 3, 10, 8000],
    ["P023", "Scarf", "Clothing", 9, 45, 600],
    ["P024", "Glue", "Stationery", 28, 160, 40],
    ["P025", "Speaker", "Electronics", 6, 30, 3000]
]

pro = pd.DataFrame(data, columns=[
    "product_code",
    "product_name",
    "category",
    "quantity",
    "available_stock",
    "price"
])

print(pro)

   product_code product_name     category  quantity  available_stock  price
0          P001       Laptop  Electronics         5               20  55000
1          P002        Shirt     Clothing        10               50   1200
2          P003         Book   Stationery        15              100    300
3          P004       Mobile  Electronics         8               30  20000
4          P005        Jeans     Clothing        12               40   1800
5          P006          Pen   Stationery        25              200     20
6          P007       Tablet  Electronics         6               25  15000
7          P008       Jacket     Clothing         7               35   2500
8          P009     Notebook   Stationery        20              150     80
9          P010   Headphones  Electronics         9               45   2000
10         P011      T-shirt     Clothing        18               60    700
11         P012       Marker   Stationery        30              180     50
12         P013      Monitor  Electronics         4               15  12000
13         P014      Sweater     Clothing        11               55   2200
14         P015       Folder   Stationery        22              140     60
15         P016     Keyboard  Electronics        10               50   1500
16         P017       Shorts     Clothing        14               65    900
17         P018       Eraser   Stationery        35              250     10
18         P019        Mouse  Electronics        13               70    800
19         P020          Cap     Clothing        16               80    400
20         P021      Stapler   Stationery        19               90    150
21         P022      Printer  Electronics         3               10   8000
22         P023        Scarf     Clothing         9               45    600
23         P024         Glue   Stationery        28              160     40
24         P025      Speaker  Electronics         6               30   3000

In [10]:
pro.set_index("product_code", inplace=True) # this function sets the index and also delets the previous valuse in that place if we use inpace = true

In [11]:
print(pro)

             product_name     category  quantity  available_stock  price
product_code
P001               Laptop  Electronics         5               20  55000
P002                Shirt     Clothing        10               50   1200
P003                 Book   Stationery        15              100    300
P004               Mobile  Electronics         8               30  20000
P005                Jeans     Clothing        12               40   1800
P006                  Pen   Stationery        25              200     20
P007               Tablet  Electronics         6               25  15000
P008               Jacket     Clothing         7               35   2500
P009             Notebook   Stationery        20              150     80
P010           Headphones  Electronics         9               45   2000
P011              T-shirt     Clothing        18               60    700
P012               Marker   Stationery        30              180     50
P013              Monitor  Electronics         4               15  12000
P014              Sweater     Clothing        11               55   2200
P015               Folder   Stationery        22              140     60
P016             Keyboard  Electronics        10               50   1500
P017               Shorts     Clothing        14               65    900
P018               Eraser   Stationery        35              250     10
P019                Mouse  Electronics        13               70    800
P020                  Cap     Clothing        16               80    400
P021              Stapler   Stationery        19               90    150
P022              Printer  Electronics         3               10   8000
P023                Scarf     Clothing         9               45    600
P024                 Glue   Stationery        28              160     40
P025              Speaker  Electronics         6               30   3000

In [12]:
pro.loc["P001"]

product_name            Laptop
category           Electronics
quantity                     5
available_stock             20
price                    55000
Name: P001, dtype: object

In [19]:
pro.loc["P002":"P008", ["price", "product_name", "available_stock"]]

              price product_name  available_stock
product_code
P002           1200        Shirt               50
P003            300         Book              100
P004          20000       Mobile               30
P005           1800        Jeans               40
P006             20          Pen              200
P007          15000       Tablet               25
P008           2500       Jacket               35

In [22]:
pro["inventory_value"] = pro['price']*pro['available_stock']
pro

,product_name,category,quantity,available_stock,price,inventory_value
product_code,,,,,,
P001,Laptop,Electronics,5,20,55000,1100000
P002,Shirt,Clothing,10,50,1200,60000
P003,Book,Stationery,15,100,300,30000
P004,Mobile,Electronics,8,30,20000,600000
P005,Jeans,Clothing,12,40,1800,72000
P006,Pen,Stationery,25,200,20,4000
P007,Tablet,Electronics,6,25,15000,375000
P008,Jacket,Clothing,7,35,2500,87500
P009,Notebook,Stationery,20,150,80,12000
P010,Headphones,Electronics,9,45,2000,90000
P011,T-shirt,Clothing,18,60,700,42000
P012,Marker,Stationery,30,180,50,9000
P013,Monitor,Electronics,4,15,12000,180000
P014,Sweater,Clothing,11,55,2200,121000
P015,Folder,Stationery,22,140,60,8400
P016,Keyboard,Electronics,10,50,1500,75000
P017,Shorts,Clothing,14,65,900,58500
P018,Eraser,Stationery,35,250,10,2500
P019,Mouse,Electronics,13,70,800,56000
P020,Cap,Clothing,16,80,400,32000
P021,Stapler,Stationery,19,90,150,13500
P022,Printer,Electronics,3,10,8000,80000
P023,Scarf,Clothing,9,45,600,27000
P024,Glue,Stationery,28,160,40,6400
P025,Speaker,Electronics,6,30,3000,90000

In [25]:
pro.loc["P001","price"] = 200000

In [26]:
pro

,product_name,category,quantity,available_stock,price,inventory_value
product_code,,,,,,
P001,Laptop,Electronics,5,20,200000,1100000
P002,Shirt,Clothing,10,50,1200,60000
P003,Book,Stationery,15,100,300,30000
P004,Mobile,Electronics,8,30,20000,600000
P005,Jeans,Clothing,12,40,1800,72000
P006,Pen,Stationery,25,200,20,4000
P007,Tablet,Electronics,6,25,15000,375000
P008,Jacket,Clothing,7,35,2500,87500
P009,Notebook,Stationery,20,150,80,12000
P010,Headphones,Electronics,9,45,2000,90000
P011,T-shirt,Clothing,18,60,700,42000
P012,Marker,Stationery,30,180,50,9000
P013,Monitor,Electronics,4,15,12000,180000
P014,Sweater,Clothing,11,55,2200,121000
P015,Folder,Stationery,22,140,60,8400
P016,Keyboard,Electronics,10,50,1500,75000
P017,Shorts,Clothing,14,65,900,58500
P018,Eraser,Stationery,35,250,10,2500
P019,Mouse,Electronics,13,70,800,56000
P020,Cap,Clothing,16,80,400,32000
P021,Stapler,Stationery,19,90,150,13500
P022,Printer,Electronics,3,10,8000,80000
P023,Scarf,Clothing,9,45,600,27000
P024,Glue,Stationery,28,160,40,6400
P025,Speaker,Electronics,6,30,3000,90000

In [27]:
pro["inventory_value"] = pro['price']*pro['available_stock']
pro

,product_name,category,quantity,available_stock,price,inventory_value
product_code,,,,,,
P001,Laptop,Electronics,5,20,200000,4000000
P002,Shirt,Clothing,10,50,1200,60000
P003,Book,Stationery,15,100,300,30000
P004,Mobile,Electronics,8,30,20000,600000
P005,Jeans,Clothing,12,40,1800,72000
P006,Pen,Stationery,25,200,20,4000
P007,Tablet,Electronics,6,25,15000,375000
P008,Jacket,Clothing,7,35,2500,87500
P009,Notebook,Stationery,20,150,80,12000
P010,Headphones,Electronics,9,45,2000,90000
P011,T-shirt,Clothing,18,60,700,42000
P012,Marker,Stationery,30,180,50,9000
P013,Monitor,Electronics,4,15,12000,180000
P014,Sweater,Clothing,11,55,2200,121000
P015,Folder,Stationery,22,140,60,8400
P016,Keyboard,Electronics,10,50,1500,75000
P017,Shorts,Clothing,14,65,900,58500
P018,Eraser,Stationery,35,250,10,2500
P019,Mouse,Electronics,13,70,800,56000
P020,Cap,Clothing,16,80,400,32000
P021,Stapler,Stationery,19,90,150,13500
P022,Printer,Electronics,3,10,8000,80000
P023,Scarf,Clothing,9,45,600,27000
P024,Glue,Stationery,28,160,40,6400
P025,Speaker,Electronics,6,30,3000,90000

In [30]:
# Create 'reorder' column
pro['reorder'] = np.where(pro['available_stock'] < 50, 'yes', 'no')

# Display the updated DataFrame
print(pro)

             product_name     category  quantity  available_stock   price  \
product_code
P001               Laptop  Electronics         5               20  200000
P002                Shirt     Clothing        10               50    1200
P003                 Book   Stationery        15              100     300
P004               Mobile  Electronics         8               30   20000
P005                Jeans     Clothing        12               40    1800
P006                  Pen   Stationery        25              200      20
P007               Tablet  Electronics         6               25   15000
P008               Jacket     Clothing         7               35    2500
P009             Notebook   Stationery        20              150      80
P010           Headphones  Electronics         9               45    2000
P011              T-shirt     Clothing        18               60     700
P012               Marker   Stationery        30              180      50
P013              Monitor  Electronics         4               15   12000
P014              Sweater     Clothing        11               55    2200
P015               Folder   Stationery        22              140      60
P016             Keyboard  Electronics        10               50    1500
P017               Shorts     Clothing        14               65     900
P018               Eraser   Stationery        35              250      10
P019                Mouse  Electronics        13               70     800
P020                  Cap     Clothing        16               80     400
P021              Stapler   Stationery        19               90     150
P022              Printer  Electronics         3               10    8000
P023                Scarf     Clothing         9               45     600
P024                 Glue   Stationery        28              160      40
P025              Speaker  Electronics         6               30    3000

              inventory_value reorder
product_code
P001                  4000000     yes
P002                    60000      no
P003                    30000      no
P004                   600000     yes
P005                    72000     yes
P006                     4000      no
P007                   375000     yes
P008                    87500     yes
P009                    12000      no
P010                    90000     yes
P011                    42000      no
P012                     9000      no
P013                   180000     yes
P014                   121000      no
P015                     8400      no
P016                    75000      no
P017                    58500      no
P018                     2500      no
P019                    56000      no
P020                    32000      no
P021                    13500      no
P022                    80000     yes
P023                    27000     yes
P024                     6400      no
P025                    90000     yes

In [31]:
# Initialize the 'reorder' column with default value 'no'
pro['reorder'] = 'no'

# Update 'reorder' to 'yes' where available_stock < 50
pro.loc[pro['available_stock'] < 50, 'reorder'] = 'yes'

# Display the updated DataFrame
print(pro)

             product_name     category  quantity  available_stock   price  \
product_code
P001               Laptop  Electronics         5               20  200000
P002                Shirt     Clothing        10               50    1200
P003                 Book   Stationery        15              100     300
P004               Mobile  Electronics         8               30   20000
P005                Jeans     Clothing        12               40    1800
P006                  Pen   Stationery        25              200      20
P007               Tablet  Electronics         6               25   15000
P008               Jacket     Clothing         7               35    2500
P009             Notebook   Stationery        20              150      80
P010           Headphones  Electronics         9               45    2000
P011              T-shirt     Clothing        18               60     700
P012               Marker   Stationery        30              180      50
P013              Monitor  Electronics         4               15   12000
P014              Sweater     Clothing        11               55    2200
P015               Folder   Stationery        22              140      60
P016             Keyboard  Electronics        10               50    1500
P017               Shorts     Clothing        14               65     900
P018               Eraser   Stationery        35              250      10
P019                Mouse  Electronics        13               70     800
P020                  Cap     Clothing        16               80     400
P021              Stapler   Stationery        19               90     150
P022              Printer  Electronics         3               10    8000
P023                Scarf     Clothing         9               45     600
P024                 Glue   Stationery        28              160      40
P025              Speaker  Electronics         6               30    3000

              inventory_value reorder
product_code
P001                  4000000     yes
P002                    60000      no
P003                    30000      no
P004                   600000     yes
P005                    72000     yes
P006                     4000      no
P007                   375000     yes
P008                    87500     yes
P009                    12000      no
P010                    90000     yes
P011                    42000      no
P012                     9000      no
P013                   180000     yes
P014                   121000      no
P015                     8400      no
P016                    75000      no
P017                    58500      no
P018                     2500      no
P019                    56000      no
P020                    32000      no
P021                    13500      no
P022                    80000     yes
P023                    27000     yes
P024                     6400      no
P025                    90000     yes

In [32]:
pro['reorder'] = 'no'  # default 'no'
pro.loc[pro['available_stock'] < 50, 'reorder'] = 'yes'  # set 'yes' where stock < 50

print(pro)

             product_name     category  quantity  available_stock   price  \
product_code
P001               Laptop  Electronics         5               20  200000
P002                Shirt     Clothing        10               50    1200
P003                 Book   Stationery        15              100     300
P004               Mobile  Electronics         8               30   20000
P005                Jeans     Clothing        12               40    1800
P006                  Pen   Stationery        25              200      20
P007               Tablet  Electronics         6               25   15000
P008               Jacket     Clothing         7               35    2500
P009             Notebook   Stationery        20              150      80
P010           Headphones  Electronics         9               45    2000
P011              T-shirt     Clothing        18               60     700
P012               Marker   Stationery        30              180      50
P013              Monitor  Electronics         4               15   12000
P014              Sweater     Clothing        11               55    2200
P015               Folder   Stationery        22              140      60
P016             Keyboard  Electronics        10               50    1500
P017               Shorts     Clothing        14               65     900
P018               Eraser   Stationery        35              250      10
P019                Mouse  Electronics        13               70     800
P020                  Cap     Clothing        16               80     400
P021              Stapler   Stationery        19               90     150
P022              Printer  Electronics         3               10    8000
P023                Scarf     Clothing         9               45     600
P024                 Glue   Stationery        28              160      40
P025              Speaker  Electronics         6               30    3000

              inventory_value reorder
product_code
P001                  4000000     yes
P002                    60000      no
P003                    30000      no
P004                   600000     yes
P005                    72000     yes
P006                     4000      no
P007                   375000     yes
P008                    87500     yes
P009                    12000      no
P010                    90000     yes
P011                    42000      no
P012                     9000      no
P013                   180000     yes
P014                   121000      no
P015                     8400      no
P016                    75000      no
P017                    58500      no
P018                     2500      no
P019                    56000      no
P020                    32000      no
P021                    13500      no
P022                    80000     yes
P023                    27000     yes
P024                     6400      no
P025                    90000     yes

In [33]:
pro['reorder'] = 'no'
pro.loc[pro['available_stock'] < 50, 'reorder'] = 'yes'

In [35]:
pd.set_option('display.max_columns', None)  # Show all columns
print(pro)

             product_name     category  quantity  available_stock   price  \
product_code
P001               Laptop  Electronics         5               20  200000
P002                Shirt     Clothing        10               50    1200
P003                 Book   Stationery        15              100     300
P004               Mobile  Electronics         8               30   20000
P005                Jeans     Clothing        12               40    1800
P006                  Pen   Stationery        25              200      20
P007               Tablet  Electronics         6               25   15000
P008               Jacket     Clothing         7               35    2500
P009             Notebook   Stationery        20              150      80
P010           Headphones  Electronics         9               45    2000
P011              T-shirt     Clothing        18               60     700
P012               Marker   Stationery        30              180      50
P013              Monitor  Electronics         4               15   12000
P014              Sweater     Clothing        11               55    2200
P015               Folder   Stationery        22              140      60
P016             Keyboard  Electronics        10               50    1500
P017               Shorts     Clothing        14               65     900
P018               Eraser   Stationery        35              250      10
P019                Mouse  Electronics        13               70     800
P020                  Cap     Clothing        16               80     400
P021              Stapler   Stationery        19               90     150
P022              Printer  Electronics         3               10    8000
P023                Scarf     Clothing         9               45     600
P024                 Glue   Stationery        28              160      40
P025              Speaker  Electronics         6               30    3000

              inventory_value reorder
product_code
P001                  4000000     yes
P002                    60000      no
P003                    30000      no
P004                   600000     yes
P005                    72000     yes
P006                     4000      no
P007                   375000     yes
P008                    87500     yes
P009                    12000      no
P010                    90000     yes
P011                    42000      no
P012                     9000      no
P013                   180000     yes
P014                   121000      no
P015                     8400      no
P016                    75000      no
P017                    58500      no
P018                     2500      no
P019                    56000      no
P020                    32000      no
P021                    13500      no
P022                    80000     yes
P023                    27000     yes
P024                     6400      no
P025                    90000     yes

In [38]:
pro['reorder'] = 'no'
pro.loc[pro['available_stock'] < 50, 'reorder'] = 'yes'
pd.set_option('display.max_columns', None)
# Option 2: Using column selection directly (simpler)
pro[["product_code","available_stock","inventory_value","reorder"]]

KeyError: "['product_code'] not in index"

In [39]:
pro_reset = pro.reset_index()  # now product_code is a column
pd.set_option('display.max_columns', None)
print(pro_reset[["product_code","available_stock","inventory_value","reorder"]])

   product_code  available_stock  inventory_value reorder
0          P001               20          4000000     yes
1          P002               50            60000      no
2          P003              100            30000      no
3          P004               30           600000     yes
4          P005               40            72000     yes
5          P006              200             4000      no
6          P007               25           375000     yes
7          P008               35            87500     yes
8          P009              150            12000      no
9          P010               45            90000     yes
10         P011               60            42000      no
11         P012              180             9000      no
12         P013               15           180000     yes
13         P014               55           121000      no
14         P015              140             8400      no
15         P016               50            75000      no
16         P017               65            58500      no
17         P018              250             2500      no
18         P019               70            56000      no
19         P020               80            32000      no
20         P021               90            13500      no
21         P022               10            80000     yes
22         P023               45            27000     yes
23         P024              160             6400      no
24         P025               30            90000     yes

In [41]:
# Using map with a lambda function
pro['reorder'] = pro['available_stock'].map(lambda x: 'yes' if x < 50 else 'no')

# Display the DataFrame with the index as product_code
pd.set_option('display.max_columns', None)

In [42]:
#pro['reoder'] = pro['available_stock'].map(priroty)
#print(pro)

In [43]:
# Using apply with a lambda
pro['priority'] = pro['available_stock'].map(
    lambda x: 'High' if x < 10 else ('Medium' if x < 30 else ('Low' if x < 50 else 'None'))
)

In [44]:
high_priority_pro = pro[pro['priority'] == 'High']

# Display only relevant columns
pd.set_option('display.max_columns', None)
print(high_priority_pro)

Empty DataFrame
Columns: [product_name, category, quantity, available_stock, price, inventory_value, reorder, priority]
Index: []

In [46]:
# Reset index so 'product_code' becomes a column
high_priority_pro_reset = high_priority_pro.reset_index()

# Now select relevant columns
columns_to_show = ['product_code', 'product_name', 'available_stock', 'priority']
pd.set_option('display.max_columns', None)
print(high_priority_pro_reset[columns_to_show])

Empty DataFrame
Columns: [product_code, product_name, available_stock, priority]
Index: []

In [48]:
pro['priority'] = pro['available_stock'].map(
    lambda x: 'High' if x < 30 else ('Medium' if x < 50 else 'Low')
)

high_priority_pro = pro[pro['priority'] == 'High']
print(high_priority_pro)

             product_name     category  quantity  available_stock   price  \
product_code
P001               Laptop  Electronics         5               20  200000
P007               Tablet  Electronics         6               25   15000
P013              Monitor  Electronics         4               15   12000
P022              Printer  Electronics         3               10    8000

              inventory_value reorder priority
product_code
P001                  4000000     yes     High
P007                   375000     yes     High
P013                   180000     yes     High
P022                    80000     yes     High

In [53]:
data1 = [
    ["P001", "Laptop", "Electronics", 5, 20, 55000],
    ["P002", "Shirt", "Clothing", None, 50, 1200],       # quantity is missing
    ["P003", "Book", "Stationery", 15, None, 300],      # available_stock is missing
    ["P004", None, "Electronics", 8, 30, 20000],        # product_name is missing
    ["P005", "Jeans", "Clothing", 12, 40, None],        # price is missing
    ["P006", "Pen", "Stationery", 25, 200, 20],
    ["P007", "Tablet", "Electronics", 6, 25, 15000],
    ["P008", "Jacket", None, 7, 35, 2500],              # category is missing
    ["P009", "Notebook", "Stationery", None, 150, 80],
    ["P010", "Headphones", "Electronics", 9, None, 2000]
]
# Create DataFrame
pro_null = pd.DataFrame(
    data1,
    columns=["product_code", "product_name", "category", "quantity", "available_stock", "price"]
)
pro_null

  product_code product_name     category  quantity  available_stock    price
0         P001       Laptop  Electronics       5.0             20.0  55000.0
1         P002        Shirt     Clothing       NaN             50.0   1200.0
2         P003         Book   Stationery      15.0              NaN    300.0
3         P004         None  Electronics       8.0             30.0  20000.0
4         P005        Jeans     Clothing      12.0             40.0      NaN
5         P006          Pen   Stationery      25.0            200.0     20.0
6         P007       Tablet  Electronics       6.0             25.0  15000.0
7         P008       Jacket         None       7.0             35.0   2500.0
8         P009     Notebook   Stationery       NaN            150.0     80.0
9         P010   Headphones  Electronics       9.0              NaN   2000.0

## handling null values
# deleting that coloumn
# deleting that row

In [57]:
#pd.fillna?()

In [58]:
pro.groupby("category")[["price",'available_stock']].mean()

                    price  available_stock
category
Clothing      1287.500000        53.750000
Electronics  29144.444444        32.777778
Stationery      88.750000       158.750000

In [59]:
pro.groupby("category").agg({'price':"mean","reorder":"count"})

                    price  reorder
category
Clothing      1287.500000        8
Electronics  29144.444444        9
Stationery      88.750000        8